# Generated by Django 3.2.14 on 2023-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_tournament_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
