# Generated by Django 3.2.14 on 2023-01-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tournament_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
