# Generated by Django 3.2.14 on 2023-01-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tournament_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='druzyna',
            field=models.ManyToManyField(blank=True, null=True, to='api.Team'),
        ),
    ]
