# Generated by Django 3.2.14 on 2023-01-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_player_druzyna'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
