# Generated by Django 3.2.14 on 2023-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_player_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='opis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
